/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class ch_section6_jcoreaudio_AudioLet */

#ifndef _Included_ch_section6_jcoreaudio_AudioLet
#define _Included_ch_section6_jcoreaudio_AudioLet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_section6_jcoreaudio_AudioLet
 * Method:    queryAvailableSamplerates
 * Signature: (IIZLjava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_ch_section6_jcoreaudio_AudioLet_queryAvailableSamplerates
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

#ifdef __cplusplus
}
#endif
#endif
