/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_synthbot_JCoreAudio_JCoreAudio */

#ifndef _Included_com_synthbot_JCoreAudio_JCoreAudio
#define _Included_com_synthbot_JCoreAudio_JCoreAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_JCoreAudio_JCoreAudio
 * Method:    fillComponentList
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_JCoreAudio_JCoreAudio_fillComponentList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_synthbot_JCoreAudio_JCoreAudio
 * Method:    fillAudioDeviceList
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_JCoreAudio_JCoreAudio_fillAudioDeviceList
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
