/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_synthbot_JCoreAudio_JCoreAudio */

#ifndef _Included_com_synthbot_JCoreAudio_JCoreAudio
#define _Included_com_synthbot_JCoreAudio_JCoreAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_JCoreAudio_JCoreAudio
 * Method:    fillAudioDeviceList
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_JCoreAudio_JCoreAudio_fillAudioDeviceList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_synthbot_JCoreAudio_JCoreAudio
 * Method:    initialise
 * Signature: ([Ljava/lang/Object;II[Ljava/lang/Object;IIIIF)J
 */
JNIEXPORT jlong JNICALL Java_com_synthbot_JCoreAudio_JCoreAudio_initialize
  (JNIEnv *, jclass, jarray, jint, jint, jarray, jint, jint, jint, jfloat);

/*
 * Class:     com_synthbot_JCoreAudio_JCoreAudio
 * Method:    play
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_JCoreAudio_JCoreAudio_play
  (JNIEnv *, jclass, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
