/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_synthbot_JCoreAudio_AudioDevice */

#ifndef _Included_com_synthbot_JCoreAudio_AudioDevice
#define _Included_com_synthbot_JCoreAudio_AudioDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_JCoreAudio_AudioDevice
 * Method:    queryLetSet
 * Signature: (Lcom/synthbot/JCoreAudio/AudioDevice;IZLjava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_JCoreAudio_AudioDevice_queryLetSet
  (JNIEnv *, jclass, jobject, jint, jboolean, jobject);

#ifdef __cplusplus
}
#endif
#endif
