/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_synthbot_JCoreAudio_AudioLet */

#ifndef _Included_com_synthbot_JCoreAudio_AudioLet
#define _Included_com_synthbot_JCoreAudio_AudioLet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_JCoreAudio_AudioLet
 * Method:    queryAvailableFormats
 * Signature: (IIZLjava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_JCoreAudio_AudioLet_queryAvailableFormats
  (JNIEnv *, jclass, jint, jint, jboolean, jobject);

#ifdef __cplusplus
}
#endif
#endif
