/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_synthbot_JCoreAudio_AudioDevice */

#ifndef _Included_com_synthbot_JCoreAudio_AudioDevice
#define _Included_com_synthbot_JCoreAudio_AudioDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_JCoreAudio_AudioDevice
 * Method:    queryLetSet
 * Signature: (Lcom/synthbot/JCoreAudio/AudioDevice;IZLjava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_com_synthbot_JCoreAudio_AudioDevice_queryLetSet
  (JNIEnv *, jclass, jobject, jint, jboolean, jobject);

/*
 * Class:     com_synthbot_JCoreAudio_AudioDevice
 * Method:    getMinimumBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_JCoreAudio_AudioDevice_getMinimumBufferSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_synthbot_JCoreAudio_AudioDevice
 * Method:    getMaximumBufferSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_JCoreAudio_AudioDevice_getMaximumBufferSize
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
